'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {projects,experience,skills,archive} from '../data/portfolio';
const SkyScene=dynamic(()=>import('./SkyScene'),{ssr:false});
const contributions:Record<string,string>={emotispace:'Emotion analysis, design logic, and generated visuals for personalized room recommendations.',signspell:'Built landmark normalization, a Random Forest classifier, and a buffered text-generation pipeline.',news:'Built news retrieval, local-LLM summaries, and scheduled email delivery.',benchmark:'Designed 100 synthetic tasks and an exact-match model evaluation pipeline.',culture:'Reimagined 15 artifacts using Stable Diffusion and ControlNet.'};
const worlds=[['home','Overview'],['psychology','Psychology'],['ai','Artificial intelligence'],['projects','Project islands'],['culture','Culture'],['hackathons','Hackathons'],['research','Research'],['technology','Technology'],['future','Next chapter']];
type Project=typeof projects[number];
export default function Portfolio(){
 const [active,setActive]=useState(0),[reduced,setReduced]=useState(false),[menu,setMenu]=useState(false),[selected,setSelected]=useState<Project|null>(null),[ready,setReady]=useState(false),[failed,setFailed]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);const opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');setReduced(m.matches);const cb=()=>setReduced(m.matches);m.addEventListener('change',cb);return()=>m.removeEventListener('change',cb)},[]);
 useEffect(()=>{const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){const i=worlds.findIndex(w=>w[0]===e.target.id);if(i>=0)setActive(i);}})},{rootMargin:'-30% 0px -30% 0px',threshold:0});document.querySelectorAll('.chapter').forEach(el=>obs.observe(el));return()=>obs.disconnect()},[]);
 useEffect(()=>{if(selected){dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[selected]);
 function openProject(id:string){opener.current=document.activeElement as HTMLElement;setSelected(projects.find(p=>p.id===id)||null)}
 function closeProject(){setSelected(null);opener.current?.focus()}
 function go(id:string){document.getElementById(id)?.scrollIntoView({behavior:reduced?'instant':'smooth'});setMenu(false)}
 return <div className={`${reduced?'portfolio reduced':'portfolio'} ${failed?'webgl-fallback':''}`} data-world={worlds[active]?.[0]}>
 <a className="skip" href="#projects">Skip to selected work</a>
 <div className="sky-backdrop" aria-hidden="true"/>{failed&&active>0&&<div className="world-art" aria-hidden="true" style={{backgroundPosition:`${((active-1)%4)*100/3}% ${Math.floor((active-1)/4)*100}%`}}/>}
 <SkyScene reduced={reduced} onReady={()=>setReady(true)} onFail={()=>{setReady(true);setFailed(true)}} onProject={openProject} onWorld={go}/>
 <div className="reading-shade" aria-hidden="true"/>
 <header className="header"><a href="#home" className="brand" onClick={()=>setMenu(false)}><span className="brand-symbol">m<span>✦</span></span><span>MONASRI<span className="brand-small">THE MIND ATLAS</span></span></a><nav aria-label="Main navigation"><a href="#psychology">About</a><a href="#projects">Selected work</a><a href="#research">Research</a><a href="#future">Contact <span>↗</span></a></nav><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="world-menu">{menu?'Close ×':'Explore worlds ⊞'}</button></header>
 {menu&&<nav id="world-menu" className="world-menu" aria-label="All worlds">{worlds.map(([id,label],i)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}><span>{String(i).padStart(2,'0')}</span>{label}<span>↗</span></a>)}</nav>}
 <div className="edge-label" aria-hidden="true">INTELLIGENCE · PEOPLE · CULTURE</div>
 <main id="journey">
 <section id="home" className="chapter hero"><div className="hero-content"><p className="eyebrow"><span className="tiny-star">✦</span> WELCOME TO MY CORNER OF THE UNIVERSE</p><h1>A world of<br/><em>connected</em><br/>curiosity.</h1><p className="hero-name">Kundeti Monasri <span> / </span> AI & ML student. Builder. Explorer.</p><p className="hero-description">I build intelligent systems—and explore the<br className="desktop-break"/> people, spaces, and cultures that give them meaning.</p><div className="hero-actions"><a className="button" href="#psychology">Begin the journey <span>↗</span></a><a className="underlink" href="#projects">View selected work</a></div></div><div className="hero-coordinate"><span>HYDERABAD, INDIA</span><strong>CONNECTED BY CURIOSITY</strong></div><div className="hero-caption"><span className="pink-dot"/> EIGHT WORLDS. ONE MIND.</div><div className="scroll-cue"><span className="scroll-line"/> SCROLL TO TRAVEL</div></section>
 <section id="psychology" className="chapter"><article className="chapter-content"><p className="eyebrow">01 / PSYCHOLOGY WORLD</p><h2>It begins<br/>with <em>people.</em></h2><p className="lead">Technology is a human question first.</p><p>I’m Monasri, studying Computer Science with AI & ML at MGIT, Hyderabad. I’m interested in how people think, learn, and relate to the spaces around them.</p><p>That curiosity takes shape in EmotiSpace: exploring how emotion, personality, and individual needs can inform room recommendations.</p><button className="underlink" onClick={()=>openProject('emotispace')}>Explore EmotiSpace ↗</button><div className="facts"><span><strong>MGIT</strong>B.Tech · 2024–2028</span><span><strong>9.05 / 10</strong>CGPA</span></div></article><div className="world-caption">THE COGNITION GARDEN <span>01 / 08</span></div></section>
 <section id="ai" className="chapter"><article className="chapter-content"><p className="eyebrow">02 / AI WORLD</p><h2>Intelligence,<br/><em>made useful.</em></h2><p className="lead">From signals to systems.</p><p>I build across computer vision, local language models, and model evaluation, connecting technical pipelines with practical interactions.</p><div className="link-list"><button onClick={()=>openProject('signspell')}><span>SignSpell AI<small>Webcam → hand landmarks → English text</small></span>↗</button><button onClick={()=>openProject('news')}><span>AI News Digest<small>News → local LLM → scheduled email</small></span>↗</button><button onClick={()=>openProject('benchmark')}><span>Learning to learn<small>Examples → model responses → evaluation</small></span>↗</button></div><a className="underlink" href="#technology">The technology behind my work ↓</a></article><div className="world-caption">THE INTELLIGENCE DISTRICT <span>02 / 08</span></div></section>
 <section id="projects" className="chapter projects-chapter"><article className="chapter-content wide-content"><p className="eyebrow">03 / PROJECT WORLDS</p><h2>Questions<br/>become <em>worlds.</em></h2><p>Five selected explorations. Each island holds a different idea.</p><div className="project-list">{projects.map(p=><button key={p.id} onClick={()=>openProject(p.id)}><span className="project-number">{p.number}</span><span><strong>{p.title}</strong><small>{p.category}</small><span className="project-summary">{p.summary}</span><span className="project-contribution"><b>My work</b> {contributions[p.id]}</span></span><span className="project-arrow">↗</span></button>)}</div><details className="archive"><summary>More experiments <span>＋</span></summary>{archive.map(([title,desc])=><div key={title}><strong>{title}</strong><p>{desc}</p></div>)}</details></article><div className="world-caption">THE ARCHIPELAGO OF IDEAS <span>03 / 08</span></div></section>
 <section id="culture" className="chapter"><article className="chapter-content"><p className="eyebrow">04 / CULTURE WORLD</p><h2>Many ways<br/>to <em>see.</em></h2><p className="lead">Code is one language.<br/>Movement, art, and stories are others.</p><p>Classical dance, writing, music, and cultural exploration shape my curiosity about human experience.</p><p>In Cultural Memory, I used Stable Diffusion and ControlNet to reimagine 15 artifacts inspired by philosophical ideas. An artistic exploration of memory—not a claim of historical reconstruction.</p><button className="underlink" onClick={()=>openProject('culture')}>Enter Cultural Memory ↗</button><div className="small-note">NATYA KAUSTUBH AWARD · 2019<br/><span>Classical dance · Mahathi Arts Academy</span></div></article><div className="world-caption">THE CULTURAL CROSSROADS <span>04 / 08</span></div></section>
 <section id="hackathons" className="chapter"><article className="chapter-content"><p className="eyebrow">05 / HACKATHON WORLD</p><h2>Ideas meet<br/><em>momentum.</em></h2><p className="lead">Experiment. Collaborate. Build.</p><p>Hackathons and ideathons are places to turn questions into experiments with other builders.</p><ul className="milestone-list"><li><span>Nationwide Ideathon<strong>IIT Patna</strong></span><small>SEP 2025<br/>PARTICIPANT</small></li><li><span>DevDual<strong>Elan & nVision, IIT Hyderabad</strong></span><small>DEC 2025<br/>PARTICIPANT</small></li><li><span>DeVQueens<strong>Hackathon</strong></span><small>APR 2026<br/>PARTICIPANT</small></li></ul><details className="archive"><summary>Internships & building experience <span>＋</span></summary>{experience.map(([date,title,org,detail])=><div key={org}><small>{date}</small><strong>{title} · {org}</strong><p>{detail}</p></div>)}</details></article><div className="world-caption">THE INVENTION YARD <span>05 / 08</span></div></section>
 <section id="research" className="chapter"><article className="chapter-content"><p className="eyebrow">06 / RESEARCH WORLD</p><h2>Better questions.<br/><em>New horizons.</em></h2><p className="lead">How do intelligent systems learn?</p><p>My 100-task learning benchmark explores rule learning, compositional reasoning, few-shot adaptation, memory, and feedback through synthetic tasks and exact-match evaluation.</p><button className="underlink" onClick={()=>openProject('benchmark')}>Explore the benchmark ↗</button><div className="community"><h3>Learning in community</h3><p><strong>Cohere community</strong><span>Member · September 2026–present</span></p><p><strong>Rewriting The Code</strong><span>Member · June 2026–present</span></p></div></article><div className="world-caption">THE OBSERVATORY <span>06 / 08</span></div></section>
 <section id="technology" className="chapter"><article className="chapter-content"><p className="eyebrow">07 / TECHNOLOGY WORLD</p><h2>Tools for<br/><em>possibility.</em></h2><p>The technologies behind the systems I build.</p><div className="skill-list">{skills.map(([name,list])=><div key={name}><h3>{name}</h3><p>{list}</p></div>)}</div><details className="archive"><summary>Selected learning <span>＋</span></summary><div><strong>CS50’s Introduction to Programming with Python</strong><p>Harvard University · July 2026</p><strong>Code in Place</strong><p>Stanford program · June 2026</p><strong>Programming Essentials in Python & Django</strong><p>TASK · March 2026</p><strong>Python for Data Science, AI & Development</strong><p>IBM · March 2025</p></div></details></article><div className="world-caption">THE SYSTEMS NEXUS <span>07 / 08</span></div></section>
 <section id="future" className="chapter future"><article className="chapter-content"><p className="eyebrow">08 / THE NEXT CHAPTER</p><h2>The horizon<br/>is an <em>invitation.</em></h2><p className="lead">From Hyderabad, with curiosity.</p><p>I’m looking toward higher education, deeper research, international collaboration, and new perspectives through cultural exploration.</p><p>These are the directions I want to grow in. The next islands are still taking shape.</p><h3 className="contact-heading">Let’s build something meaningful.</h3><div className="contact-links"><a href="https://www.linkedin.com/in/kundeti-monasri-3650ba326" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/Monasri29-hub" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div><a className="underlink" href="#home">Return to the whole world ↑</a></article><div className="world-caption">DIFFERENT WORLDS. ONE CONNECTED CURIOSITY. <span>08 / 08</span></div></section>
 </main>
 <footer className="travel-bar"><div className="travel-status"><span className="tiny-star">✦</span><span>{!ready?'Opening the atlas…':active===0?'YOUR JOURNEY STARTS HERE':worlds[active]?.[1]}</span></div><nav aria-label="World navigation">{worlds.map(([id,label],i)=><a key={id} href={`#${id}`} aria-label={label} aria-current={active===i?'location':undefined} className={active===i?'active':''}><span>{String(i).padStart(2,'0')}</span><span className="world-tooltip">{label}</span></a>)}</nav><button onClick={()=>setReduced(!reduced)} aria-pressed={reduced}>{reduced?'Motion off':'Motion on'} <span>{reduced?'▷':'Ⅱ'}</span></button></footer>
 <dialog ref={dialog} className="project-dialog" onCancel={closeProject} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeProject()}}}><button className="close-dialog" onClick={closeProject} aria-label="Close project details">×</button>{selected&&<article><p className="eyebrow">PROJECT {selected.number} / {selected.category}</p><h2>{selected.title}</h2><p className="lead">{selected.summary}</p><p>{selected.description}</p><h3>The question</h3><p>{selected.problem}</p><h3>What I built</h3><p>{selected.contribution}</p><h3>The workflow</h3><ol className="workflow">{selected.flow.map(s=><li key={s}>{s}</li>)}</ol><h3>The outcome</h3><p>{selected.outcome}</p><div className="tags">{selected.tech.map(t=><span key={t}>{t}</span>)}</div><a className="underlink" href="https://github.com/Monasri29-hub" target="_blank" rel="noopener noreferrer">Explore my GitHub profile ↗</a></article>}</dialog>
 </div>
}
