'use client';
import {useEffect,useRef} from 'react';
import * as T from 'three';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
type Props={reduced:boolean;onReady:()=>void;onFail:()=>void;onProject:(id:string)=>void;onWorld:(id:string)=>void};
const destinations=[{id:'psychology',name:'PSYCHOLOGY',p:[-14,1,12],r:5},{id:'ai',name:'AI WORLD',p:[5,3,0],r:7},{id:'projects',name:'PROJECT ISLANDS',p:[15,0,19],r:3.5},{id:'culture',name:'CULTURE',p:[-17,4,-11],r:4.5},{id:'hackathons',name:'HACKATHONS',p:[21,5,-6],r:4.8},{id:'research',name:'RESEARCH',p:[0,7,-24],r:5},{id:'technology',name:'TECHNOLOGY',p:[-25,2,-30],r:4.5},{id:'future',name:'NEXT CHAPTER',p:[17,9,-38],r:5}];
const rnd=(i:number)=>{const n=Math.sin(i*127.1+311.7)*43758.5453;return n-Math.floor(n)};
export default function SkyScene(props:Props){
 const canvas=useRef<HTMLCanvasElement>(null),labels=useRef<HTMLDivElement>(null),current=useRef(props);current.current=props;
 useEffect(()=>{if(!canvas.current)return;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({canvas:canvas.current,alpha:true,antialias:true,powerPreference:'high-performance'});}catch{current.current.onFail();return;}
 gsap.registerPlugin(ScrollTrigger);const mobile=innerWidth<720;renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.2:1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.28;
 const scene=new T.Scene();scene.fog=new T.FogExp2('#b6deef',.006);const camera=new T.PerspectiveCamera(mobile?53:45,innerWidth/innerHeight,.2,300);const sunlight=new T.DirectionalLight('#fff4dc',3.2);sunlight.position.set(-30,60,30);scene.add(sunlight,new T.HemisphereLight('#e8f9ff','#497585',2.5));const rim=new T.DirectionalLight('#8ce6ff',1.6);rim.position.set(30,12,-30);scene.add(rim);
 const white=new T.MeshStandardMaterial({color:'#d3e9ef',metalness:.6,roughness:.32});const glass=new T.MeshStandardMaterial({color:'#30768d',metalness:.72,roughness:.19});const stone=new T.MeshStandardMaterial({color:'#4e7883',roughness:.94,flatShading:true});const grass=new T.MeshStandardMaterial({color:'#648f85',roughness:.95,flatShading:true});const pink=new T.MeshBasicMaterial({color:'#ff7fd4'}),cyan=new T.MeshBasicMaterial({color:'#78f4ff'});const gold=new T.MeshStandardMaterial({color:'#d9c4a2',metalness:.45,roughness:.4});
 const box=new T.BoxGeometry(1,1,1),sphere=new T.IcosahedronGeometry(1,1);const groups:T.Group[]=[],clickables:T.Object3D[]=[],rotators:T.Object3D[]=[],routes:{curve:T.CatmullRomCurve3;dot:T.Mesh;offset:number}[]=[];
 function mesh(g:T.BufferGeometry,m:T.Material,parent:T.Object3D,x=0,y=0,z=0,sx=1,sy=1,sz=1){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);parent.add(o);return o;}
 function line(points:T.Vector3[],color:string,parent:T.Object3D,opacity=.65){const o=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color,transparent:true,opacity}));parent.add(o);return o;}
 function ring(parent:T.Object3D,r:number,y:number,mat:T.Material,thickness=.025){const o=mesh(new T.TorusGeometry(r,thickness,5,80),mat,parent,0,y);o.rotation.x=Math.PI/2;return o;}
 function beam(parent:T.Object3D,x:number,y:number,z:number,height:number,mat:T.Material){mesh(new T.CylinderGeometry(.023,.04,height,5),mat,parent,x,y+height/2,z);mesh(new T.CylinderGeometry(.12,.2,height,6),new T.MeshBasicMaterial({color:mat===pink?'#ff74d0':'#6deeff',transparent:true,opacity:.12,depthWrite:false}),parent,x,y+height/2,z);}
 function island(x:number,y:number,z:number,r:number,seed:number,id:string){const g=new T.Group();g.position.set(x,y,z);g.userData={world:id,baseY:y};scene.add(g);groups.push(g);const rockGeo=new T.CylinderGeometry(r,r*.18,r*1.65,11,3);const pos=rockGeo.attributes.position;for(let i=0;i<pos.count;i++){const px=pos.getX(i),pz=pos.getZ(i);const a=Math.atan2(pz,px);const jitter=1+.13*Math.sin(a*5+seed)+.06*Math.cos(a*9);pos.setXYZ(i,px*jitter,pos.getY(i),pz*jitter);}rockGeo.computeVertexNormals();mesh(rockGeo,stone,g,0,-r*.8);const topColors:Record<string,string>={psychology:'#b5a9cd',ai:'#688e9e',projects:'#a3a1c0',culture:'#cead86',hackathons:'#b08f79',research:'#8b8caf',technology:'#6ca89d',future:'#c8c7b4'};mesh(new T.CylinderGeometry(r*1.02,r,.27,id==='hackathons'?6:id==='technology'?4:32),new T.MeshStandardMaterial({color:topColors[id]??'#648f85',roughness:.75}),g,0,.03);ring(g,r*.91,.21,cyan,.023);ring(g,r*.94,.17,white,.065);
 for(let k=0;k<13;k++){const a=k/13*Math.PI*2;const radius=r*(.76+rnd(k+seed)*.16);const h=r*(.3+rnd(k+seed+15));mesh(new T.ConeGeometry(.12+rnd(k+seed+11)*.27,h,5),stone,g,Math.cos(a)*radius,-h*.65,Math.sin(a)*radius);if(k%3===0)beam(g,Math.cos(a)*radius,-h*1.5,Math.sin(a)*radius,h*1.3,cyan);}
 for(let k=0;k<(mobile?13:28);k++){const a=rnd(k+seed+340)*Math.PI*2,rr=r*(.65+rnd(k+seed+630)*.27);const h=.12+rnd(k+seed+330)*.3;mesh(sphere,grass,g,Math.cos(a)*rr,h*.5+.15,Math.sin(a)*rr,h*1.3,h,h*1.3);}
 clickables.push(g);return g;}
 function city(g:T.Group,r:number,n:number,seed:number){const windows:T.Matrix4[]=[];const transform=new T.Object3D();for(let i=0;i<n;i++){const a=rnd(i+seed)*Math.PI*2,rr=Math.sqrt(rnd(i+seed+99))*r*.67;const x=Math.cos(a)*rr,z=Math.sin(a)*rr;const w=.24+rnd(i+seed+153)*.55,h=1.1+Math.pow(1-rr/r,2)*(3+rnd(i+seed+56)*8);mesh(box,i%3===0?glass:white,g,x,h/2+.2,z,w,h,w*.8);mesh(box,white,g,x,h+.35,z,w*.6,.3,w*.6);if(i%4===0)beam(g,x,h+.45,z,1.5+rnd(i+seed+55)*3,pink);else mesh(box,cyan,g,x+w*.52,h*.55,z,.018,h*.7,.025);for(let f=.5;f<h-.2;f+=.32){transform.position.set(x,f,z+w*.411);transform.scale.set(w*.8,.035,.014);transform.updateMatrix();windows.push(transform.matrix.clone());}}
 const im=new T.InstancedMesh(box,new T.MeshBasicMaterial({color:'#99edfa',transparent:true,opacity:.68}),windows.length);windows.forEach((m,i)=>im.setMatrixAt(i,m));g.add(im);}
 function neural(g:T.Group){const net=new T.Group();net.position.y=2.7;g.add(net);const points:T.Vector3[]=[];for(let i=0;i<75;i++){const a=rnd(i+711)*Math.PI*2,phi=Math.acos(2*rnd(i+212)-1);const p=new T.Vector3(Math.sin(phi)*Math.cos(a)*1.8,Math.cos(phi)*1.4,Math.sin(phi)*Math.sin(a)*1.3);points.push(p);mesh(sphere,i%5?cyan:pink,net,p.x,p.y,p.z,.035,.035,.035);}for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++)if(points[i].distanceTo(points[j])<.85)line([points[i],points[j]],'#81dce8',net,.6);rotators.push(net);for(let i=0;i<3;i++){const o=ring(g,2+i*.18,2.7,white,.035);o.rotation.set(i*.8,.4,i*.7);}mesh(new T.CylinderGeometry(1.5,1.9,.3,40),white,g,0,.4);}
 function pavilion(g:T.Group,r:number){for(let i=0;i<8;i++){const a=i/8*Math.PI*2;mesh(new T.CylinderGeometry(.16,.2,2.3,10),white,g,Math.cos(a)*r,1.3,Math.sin(a)*r);mesh(new T.ConeGeometry(.35,.8,6),gold,g,Math.cos(a)*r,2.8,Math.sin(a)*r);}ring(g,r,2.5,gold,.12);mesh(new T.SphereGeometry(r*.85,24,12,0,Math.PI*2,0,Math.PI/2),new T.MeshStandardMaterial({color:'#bde4e8',metalness:.4,roughness:.25,transparent:true,opacity:.7}),g,0,2.5);}
 // Topic-specific architectural vocabularies. Only AI uses a city skyline.
 const rose=new T.MeshStandardMaterial({color:'#d8a3cb',roughness:.45,metalness:.2});
 const amber=new T.MeshStandardMaterial({color:'#e9a66f',roughness:.4,metalness:.3});
 const violet=new T.MeshBasicMaterial({color:'#bcabff'});
 const teal=new T.MeshStandardMaterial({color:'#51bba9',roughness:.4,metalness:.4});
 function ribbon(g:T.Object3D,points:T.Vector3[],mat:T.Material,thickness=.055){return mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points),45,thickness,7,false),mat,g)}
 function globe(g:T.Object3D,y:number,r:number){const orb=new T.Group();orb.position.y=y;g.add(orb);mesh(new T.SphereGeometry(r,32,20),new T.MeshStandardMaterial({color:'#358caa',metalness:.3,roughness:.3,transparent:true,opacity:.84}),orb);for(let i=0;i<6;i++){const m=mesh(new T.TorusGeometry(r*1.012,.017,4,70),gold,orb);m.rotation.y=i*Math.PI/6;}for(let i=-2;i<=2;i++){const lat=i*Math.PI/7;ring(orb,Math.cos(lat)*r*1.018,Math.sin(lat)*r,cyan,.015);}orb.userData.speed=.000035;rotators.push(orb);return orb}
 destinations.forEach((d,i)=>{
 const g=island(d.p[0],d.p[1],d.p[2],d.r,i*110+4,d.id);
 if(d.id==='psychology'){
 neural(g);
 for(let j=0;j<3;j++){const x=(j-1)*2.4,z=j%2?1.5:-.8;mesh(new T.SphereGeometry(.33,16,12),rose,g,x,1.95,z);mesh(new T.CapsuleGeometry(.3,.65,6,12),rose,g,x,1.1,z,.9,1, .6);const petal=mesh(new T.TorusGeometry(2.8,.09,10,70,Math.PI*1.6),rose,g,0,2.3);petal.rotation.set(j*.8,.3,j*1.2);}
 for(let j=0;j<9;j++){const a=j*Math.PI*2/9;const fragment=mesh(box,new T.MeshStandardMaterial({color:j%2?'#f0c5e0':'#b9c9ed',roughness:.4}),g,Math.cos(a)*3.1,1.4+Math.sin(a*2)*.55,Math.sin(a)*3.1,.45,.65,.09);fragment.rotation.y=-a;}
 ribbon(g,[new T.Vector3(-4,.4,0),new T.Vector3(-1,.6,2),new T.Vector3(1,.4,-2),new T.Vector3(4,.5,0)],pink,.06);
 }
 if(d.id==='ai'){
 city(g,d.r,mobile?28:48,130);const core=mesh(new T.IcosahedronGeometry(1.4,2),cyan,g,0,8.2);core.userData.speed=.00015;rotators.push(core);ring(g,2.1,8,white,.06);beam(g,0,7,0,7,pink);
 for(let j=0;j<3;j++){const panel=mesh(box,new T.MeshBasicMaterial({color:'#55cef7',transparent:true,opacity:.23,side:T.DoubleSide}),g,(j-1)*3,3,3.8,2,1.5,.03);panel.rotation.y=.15*(j-1);for(let k=0;k<4;k++)mesh(box,cyan,panel,0,(k-1.5)*.19,.7,.75,.018,.02);}
 }
 if(d.id==='projects'){
 for(let j=0;j<5;j++){const a=j/5*Math.PI*2;mesh(new T.CylinderGeometry(.7,.9,.25,6),white,g,Math.cos(a)*1.9,.4,Math.sin(a)*1.9);line([new T.Vector3(0,.6,0),new T.Vector3(Math.cos(a)*1.9,.6,Math.sin(a)*1.9)],'#b8a6ff',g)}
 const idea=mesh(new T.OctahedronGeometry(.9),violet,g,0,1.6);rotators.push(idea);
 }
 if(d.id==='culture'){
 // Open amphitheatre and musical ribbons around an armillary globe.
 for(let j=0;j<4;j++){const tier=mesh(new T.TorusGeometry(2+j*.4,.18,8,60,Math.PI*1.5),j%2?gold:amber,g,0,.35+j*.24);tier.rotation.x=Math.PI/2;}
 globe(g,2.8,1.35);
 for(let j=0;j<3;j++){const pts=[];for(let k=0;k<22;k++){const x=-3.5+k/3;pts.push(new T.Vector3(x,1+j*.55+Math.sin(x*1.25)*.55,2.4+j*.1))}ribbon(g,pts,j%2?rose:gold,.055)}
 for(let j=0;j<4;j++){const a=j/4*Math.PI*2;const arch=mesh(new T.TorusGeometry(.7,.13,10,36,Math.PI),amber,g,Math.cos(a)*3.5,.4,Math.sin(a)*3.5);arch.rotation.y=a;}
 }
 if(d.id==='hackathons'){
 const deck=mesh(box,glass,g,0,.2,0,6,.25,5);ring(g,2.3,.55,amber,.15);
 for(let j=0;j<4;j++){const x=j%2?2.3:-2.3,z=j<2?-1.6:1.6;mesh(box,white,g,x,1,z,1.4,.16,1);mesh(box,glass,g,x,.6,z,.15,.8,.6);const prototype=mesh(new T.OctahedronGeometry(.45),j%2?pink:amber,g,x,1.6,z);prototype.userData.speed=.00065;rotators.push(prototype);}
 mesh(box,amber,g,-3,2.8,0,.18,5,.18);mesh(box,amber,g,0,5.3,0,6.2,.18,.18);mesh(box,white,g,1.6,4.3,0,.05,2,.05);const moving=mesh(new T.TorusKnotGeometry(.65,.12,60,8),pink,g,1.6,3.2,0);moving.userData.speed=.0005;rotators.push(moving);
 }
 if(d.id==='research'){
 mesh(new T.CylinderGeometry(1.5,1.8,.65,32),white,g,-1,.5,0);mesh(new T.SphereGeometry(1.4,24,16,0,Math.PI*2,0,Math.PI/2),glass,g,-1,.8,0);
 const telescope=new T.Group();g.add(telescope);telescope.position.set(-1,1.5,0);telescope.rotation.z=-.6;mesh(new T.CylinderGeometry(.27,.4,2.4,16),white,telescope,0,1);
 const starMap=new T.Group();g.add(starMap);starMap.position.set(.7,3.8,0);const stars=[];for(let j=0;j<18;j++){const a=j*2.399;const p=new T.Vector3(Math.cos(a)*(1+j*.11),Math.sin(a)*(1+j*.08),Math.sin(j)*.6);stars.push(p);mesh(sphere,violet,starMap,p.x,p.y,p.z,.07,.07,.07);if(j>0)line([stars[j-1],p],'#b8b0f8',starMap,.6)}starMap.userData.speed=.000022;rotators.push(starMap);const arc=mesh(new T.TorusGeometry(3.8,.035,6,90,Math.PI*1.7),violet,g,0,3);arc.rotation.y=.35;
 }
 if(d.id==='technology'){
 // Layered frameworks, with distributed modules connected across levels.
 for(let layer=0;layer<3;layer++){const framework=new T.Group();g.add(framework);framework.position.y=.6+layer*1.1;framework.rotation.y=layer*.22;const edge=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(5-layer*.6,.15,3.5)),new T.LineBasicMaterial({color:'#5adebf'}));framework.add(edge);for(let j=0;j<4;j++){const x=j%2?1.4:-1.4,z=j<2?-1:1;mesh(box,teal,framework,x,.3,z,.55,.5,.65);line([new T.Vector3(x,.3,z),new T.Vector3(0,.3,0)],'#77efe1',framework)}mesh(box,white,framework,0,.4,0,.75,.7,.75);}
 const orbit=new T.Group();g.add(orbit);orbit.position.y=2.8;for(let j=0;j<6;j++){const a=j/6*Math.PI*2;mesh(box,j%2?teal:white,orbit,Math.cos(a)*3.3,Math.sin(a)*.4,Math.sin(a)*3.3,.35,.35,.35)}orbit.userData.speed=.00015;rotators.push(orbit);
 }
 if(d.id==='future'){
 // Sparse open horizon: a globe and incomplete routes rather than buildings.
 globe(g,3.4,2.1);mesh(new T.CylinderGeometry(2.5,2.8,.15,48),white,g,0,.4);ring(g,2.7,.55,gold,.035);
 for(let j=0;j<4;j++){const angle=-1+j*.7;const points=[new T.Vector3(0,.6,0),new T.Vector3(Math.cos(angle)*3,2,Math.sin(angle)*3),new T.Vector3(Math.cos(angle)*8,4+j*.6,Math.sin(angle)*8)];ribbon(g,points,j%2?cyan:gold,.025);const p=points[2];mesh(new T.SphereGeometry(.1,8,6),gold,g,p.x,p.y,p.z);}
 }
 });
 // Five individual project districts, joined to the project hub.
 const projectIds=['emotispace','signspell','news','benchmark','culture'];const projectPositions=[[10,-1,27],[21,2,25],[25,-1,16],[15,4,9],[7,1,20]];
 projectPositions.forEach((p,i)=>{const g=island(p[0],p[1],p[2],2.15,1100+i*23,'projects');g.userData.project=projectIds[i];if(i===0){mesh(box,white,g,0,.4,0,2.6,.2,2);mesh(box,glass,g,-1.25,1.1,0,.1,1.3,2);mesh(box,white,g,0,.8,-.6,1.5,.6,.7);mesh(box,white,g,.75,1.2,-.6,.1,.8,.7);ring(g,1.1,2,pink,.03)}else if(i===1){for(let j=0;j<5;j++)mesh(new T.CapsuleGeometry(.13,.5+j%3*.22,3,6),white,g,(j-2)*.33,1.4+(j%3)*.12,0);mesh(box,glass,g,0,.7,0,1.6,.8,.3);beam(g,0,.1,0,3,cyan)}else if(i===2){for(let j=0;j<3;j++){const m=mesh(box,white,g,(j-1)*1.1,1.1,0,.65,1.3,.65);mesh(box,cyan,m,0,.15,.51,.7,.1,.03)}ring(g,1.6,.4,pink,.025)}else if(i===3){for(let row=0;row<3;row++)for(let col=0;col<3;col++){const tile=mesh(box,(row+col)%2?violet:white,g,(col-1)*.7,.5+row*.5,(row-1)*.45,.5,.18,.5);if(row===2)mesh(new T.OctahedronGeometry(.18),cyan,g,(col-1)*.7,1.9,(row-1)*.45);}ring(g,1.65,.3,violet,.04)}else{pavilion(g,1);mesh(new T.CylinderGeometry(.32,.5,1.1,12),gold,g,0,1,0)}});
 function connect(a:number[],b:number[],i:number){const av=new T.Vector3(a[0],a[1]+.28,a[2]),bv=new T.Vector3(b[0],b[1]+.28,b[2]);const mid=av.clone().lerp(bv,.5);mid.y+=1.4;const curve=new T.CatmullRomCurve3([av,mid,bv]);mesh(new T.TubeGeometry(curve,50,.022,4,false),i%2?pink:cyan,scene);const outer=mesh(new T.TubeGeometry(curve,50,.1,4,false),new T.MeshBasicMaterial({color:i%2?'#ff9cde':'#8ff5ff',transparent:true,opacity:.12,depthWrite:false}),scene);const dot=mesh(sphere,white,scene,0,0,0,.09,.09,.09);routes.push({curve,dot,offset:i*.13});}
 [[0,1],[1,2],[0,3],[1,4],[3,5],[5,6],[5,7],[4,7],[2,4]].forEach(([a,b],i)=>connect(destinations[a].p,destinations[b].p,i));projectPositions.forEach((p,i)=>connect(destinations[2].p,p,i));
 // Atmospheric cloud sprites: soft depth without expensive volumetric ray marching.
 const cloudCanvas=document.createElement('canvas');cloudCanvas.width=128;cloudCanvas.height=128;const ctx=cloudCanvas.getContext('2d')!;const gradient=ctx.createRadialGradient(64,64,4,64,64,64);gradient.addColorStop(0,'rgba(255,255,255,.7)');gradient.addColorStop(.35,'rgba(246,253,255,.45)');gradient.addColorStop(1,'rgba(244,252,255,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);const texture=new T.CanvasTexture(cloudCanvas);const clouds:T.Sprite[]=[];for(let i=0;i<(mobile?30:75);i++){const sprite=new T.Sprite(new T.SpriteMaterial({map:texture,color:'#f0fbff',transparent:true,opacity:.45,depthWrite:false}));sprite.position.set((rnd(i+5000)-.5)*140,-8-rnd(i+5300)*10,(rnd(i+6000)-.5)*140);const size=10+rnd(i+5500)*20;sprite.scale.set(size*1.8,size,1);scene.add(sprite);clouds.push(sprite);}
 // An overview followed by one camera destination per chapter.
 const overview={x:48,y:32,z:60,lx:0,ly:2,lz:-5};const state={...overview};const target=new T.Vector3();let progress=0;let trigger:ScrollTrigger|undefined;
 function configure(){trigger?.kill();const sections=Array.from(document.querySelectorAll<HTMLElement>('.chapter'));const starts=sections.map(s=>s.offsetTop);trigger=ScrollTrigger.create({trigger:'#journey',start:'top top',end:'bottom bottom',onUpdate:()=>{const sy=window.scrollY;let index=0;while(index<starts.length-2&&sy>=starts[index+1])index++;const fraction=Math.min(1,Math.max(0,(sy-starts[index])/(starts[index+1]-starts[index]||innerHeight)));progress=index+fraction;}});}
 function waypoint(index:number){if(index===0)return overview;const d=destinations[Math.min(index-1,7)];return {x:d.p[0]+(mobile?14:17),y:d.p[1]+10,z:d.p[2]+22,lx:d.p[0]-(mobile?4:7),ly:d.p[1]+1.7,lz:d.p[2]};}
 const labelElements=destinations.map(d=>{const el=document.createElement('button');el.className='island-label';el.textContent=d.name;el.setAttribute('aria-label',`Visit ${d.name.toLowerCase()}`);el.onclick=()=>current.current.onWorld(d.id);labels.current?.appendChild(el);return el});
 let pointerX=0,pointerY=0;const onPointer=(e:PointerEvent)=>{pointerX=(e.clientX/innerWidth-.5)*.8;pointerY=(e.clientY/innerHeight-.5)*.3};window.addEventListener('pointermove',onPointer,{passive:true});const ray=new T.Raycaster(),ndc=new T.Vector2();const onClick=(e:MouseEvent)=>{ndc.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(ndc,camera);const hit=ray.intersectObjects(clickables,true)[0];if(hit){let o:T.Object3D|null=hit.object;while(o&&!o.userData.world)o=o.parent;if(o?.userData.project)current.current.onProject(o.userData.project);else if(o?.userData.world)current.current.onWorld(o.userData.world)}};canvas.current.addEventListener('click',onClick);
 let raf=0,last=0,lastReducedProgress=-1;const v=new T.Vector3();function frame(time:number){raf=requestAnimationFrame(frame);if(document.hidden||time-last<1000/(mobile?24:40))return;last=time;const reduced=current.current.reduced;if(reduced&&lastReducedProgress===progress)return;lastReducedProgress=reduced?progress:-1;const idx=Math.min(7,Math.floor(progress)),f=progress-idx;const a=waypoint(idx),b=waypoint(idx+1);const eased=gsap.parseEase('power2.inOut')(Math.min(f,1));(Object.keys(state) as (keyof typeof state)[]).forEach(k=>{const desired=a[k]+(b[k]-a[k])*eased;state[k]=reduced?desired:state[k]+(desired-state[k])*.08});camera.position.set(state.x+(reduced?0:pointerX),state.y+(reduced?0:pointerY),state.z);target.set(state.lx,state.ly,state.lz);camera.lookAt(target);if(!reduced){groups.forEach((g,i)=>g.position.y=g.userData.baseY+Math.sin(time*.00035+i)*.11);rotators.forEach((o,i)=>o.rotation.y=time*(o.userData.speed??.0001)*(i%2?-1:1));routes.forEach(r=>r.dot.position.copy(r.curve.getPoint((time*.00004+r.offset)%1)));}renderer.render(scene,camera);destinations.forEach((d,i)=>{v.set(d.p[0],d.p[1]+d.r*.7+2,d.p[2]).project(camera);const x=(v.x*.5+.5)*innerWidth,y=(-v.y*.5+.5)*innerHeight;const show=!mobile&&progress<.25&&v.z<1&&x>innerWidth*.5&&x<innerWidth-90&&y>130&&y<innerHeight-180;labelElements[i].style.opacity=show?'1':'0';labelElements[i].style.pointerEvents=show?'auto':'none';labelElements[i].style.visibility=show?'visible':'hidden';labelElements[i].style.transform=`translate(${x}px,${y}px)`;});}
 const resize=()=>{lastReducedProgress=-1;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);ScrollTrigger.refresh()};window.addEventListener('resize',resize);const contextLost=(e:Event)=>{e.preventDefault();current.current.onFail()};canvas.current.addEventListener('webglcontextlost',contextLost);configure();const ro=new ResizeObserver(()=>{configure();ScrollTrigger.refresh()});const journey=document.getElementById('journey');if(journey)ro.observe(journey);raf=requestAnimationFrame(frame);current.current.onReady();
 return()=>{cancelAnimationFrame(raf);trigger?.kill();ro.disconnect();window.removeEventListener('resize',resize);window.removeEventListener('pointermove',onPointer);canvas.current?.removeEventListener('click',onClick);canvas.current?.removeEventListener('webglcontextlost',contextLost);labelElements.forEach(e=>e.remove());const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>();scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line||o instanceof T.Sprite){if('geometry'in o)geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m))}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());texture.dispose();renderer.dispose();};
 },[]);
 return <><canvas ref={canvas} className="sky-canvas" aria-label="Connected floating islands representing psychology, AI, projects, culture, hackathons, research, technology and future goals" role="img"/><div ref={labels} className="island-labels"/></>
}
